### ISSUE TITLE
BNB network: Safe UI not loading

### ISSUE THREAD

**Issue by reyserveth** [safe-global/safe-services-status#375]
![image](https://user-images.githubusercontent.com/114401730/209637101-27b30f4e-8461-4ab4-b441-7a90830550e4.png)

Issue: Safe UI not loading. 
Network: BNB
User Safe address: 0x07f5fc7548de8bC0CA003D8Bf8D8DD4d1ae515EB
T/S done:
Tried multiple browsers.
Cleared cache and cookies.
Issue is more than 24 hrs already. Started 26-Dec-2022

**Comment by med3000** [comment]
@reyserveth I believe this is in the wrong repo - please be sure to use https://github.com/5afe/safe-support thanks.
