### ISSUE TITLE
Take back ownership issue

### ISSUE THREAD

**Issue by reyserveth** [safe-global/safe-services-status#378]
I would like to ask for your assistance with regard to user's issue with Take back ownership. He is getting an error "Cannot estimate gas"

https://app.intercom.com/a/inbox/km54f6ih/inbox/admin/5562590/conversation/36000022054?view=List

**Comment by inahlikenoother** [comment]
Hi team, I have a user getting the same error https://app.intercom.com/a/inbox/km54f6ih/inbox/admin/5304360/conversation/36000022045?view=List

**Comment by moisses89** [comment]
@reyserveth @inahlikenoother this project is not for support, move this issue to the correct project https://github.com/5afe/safe-support

**Comment by reyserveth** [comment]
moved

**Comment by med3000** [comment]
thanks @reyserveth will delete this as duplicate :)
